# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=2)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('num_subgroups', models.PositiveSmallIntegerField(default=0)),
                ('degree', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=200, validators=['validate_comma_separated_integer_list'])),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('t_hours', models.PositiveSmallIntegerField(default=0)),
                ('p_hours', models.PositiveSmallIntegerField(default=0)),
                ('acronym', models.CharField(max_length=10)),
                ('speciality', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('semester', models.PositiveSmallIntegerField(default=0)),
                ('degree', models.CharField(max_length=200)),
                ('students', models.PositiveSmallIntegerField(default=0)),
                ('p_classes', models.ManyToManyField(to='timetables.PracticeClassroom')),
            ],
        ),
    ]
