# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='p_hours',
            new_name='phours',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='t_hours',
            new_name='thours',
        ),
    ]
