# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_auto_20170819_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='num_subgroups',
            new_name='numsubgroups',
        ),
    ]
