# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_auto_20170819_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='p_classes',
            new_name='pclasses',
        ),
    ]
