# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_auto_20170819_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='pclasses',
            new_name='practiceclassroom',
        ),
    ]
