# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0005_auto_20170819_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PracticeClassroom',
        ),
        migrations.AlterField(
            model_name='subject',
            name='practiceclassroom',
            field=models.ManyToManyField(to='timetables.Classroom'),
        ),
    ]
