# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0007_auto_20170820_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='ispractice',
            field=models.BooleanField(default=True),
        ),
    ]
