# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0008_classroom_ispractice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
    ]
