# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0009_auto_20170827_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Subjects',
        ),
    ]
