# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0011_cell_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='classroom',
        ),
        migrations.AddField(
            model_name='cell',
            name='classroom',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.RemoveField(
            model_name='cell',
            name='subject',
        ),
        migrations.AddField(
            model_name='cell',
            name='subject',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
