# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0012_auto_20170902_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='group',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
